# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-netf

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish -c Release --output ./Release
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        # Deployment destination server & path. Formatted as protocol://domain.com:port/full/destination/path/
        server: ${{ secrets.FTP_SERVER }}
        # FTP account username
        username: ${{ secrets.FTP_USERNAME }}
        # FTP account password
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftps
        port: 2100
        dry-run: false
        # The local folder to copy, defaults to root project folder
        local-dir: ./Release/
        server-dir: /
